{"url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/19", "repository_url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning", "labels_url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/19/labels{/name}", "comments_url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/19/comments", "events_url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/19/events", "html_url": "https://github.com/PyTorchLightning/pytorch-lightning/issues/19", "id": 472633714, "node_id": "MDU6SXNzdWU0NzI2MzM3MTQ=", "number": 19, "title": "AttributeError: 'Experiment' object has no attribute 'get_meta_copy'", "user": {"login": "PeterouZh", "id": 26176709, "node_id": "MDQ6VXNlcjI2MTc2NzA5", "avatar_url": "https://avatars.githubusercontent.com/u/26176709?v=4", "gravatar_id": "", "url": "https://api.github.com/users/PeterouZh", "html_url": "https://github.com/PeterouZh", "followers_url": "https://api.github.com/users/PeterouZh/followers", "following_url": "https://api.github.com/users/PeterouZh/following{/other_user}", "gists_url": "https://api.github.com/users/PeterouZh/gists{/gist_id}", "starred_url": "https://api.github.com/users/PeterouZh/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/PeterouZh/subscriptions", "organizations_url": "https://api.github.com/users/PeterouZh/orgs", "repos_url": "https://api.github.com/users/PeterouZh/repos", "events_url": "https://api.github.com/users/PeterouZh/events{/privacy}", "received_events_url": "https://api.github.com/users/PeterouZh/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2019-07-25T02:29:40Z", "updated_at": "2019-07-25T13:57:18Z", "closed_at": "2019-07-25T13:57:18Z", "author_association": "NONE", "active_lock_reason": null, "body": "https://github.com/williamFalcon/pytorch-lightning/blob/b8c7baa8acce9e363c33d2580eb1abcca322a211/pytorch_lightning/models/trainer.py#L419\r\nI encountered this problem when I used ddp. ", "closed_by": {"login": "williamFalcon", "id": 3640001, "node_id": "MDQ6VXNlcjM2NDAwMDE=", "avatar_url": "https://avatars.githubusercontent.com/u/3640001?v=4", "gravatar_id": "", "url": "https://api.github.com/users/williamFalcon", "html_url": "https://github.com/williamFalcon", "followers_url": "https://api.github.com/users/williamFalcon/followers", "following_url": "https://api.github.com/users/williamFalcon/following{/other_user}", "gists_url": "https://api.github.com/users/williamFalcon/gists{/gist_id}", "starred_url": "https://api.github.com/users/williamFalcon/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/williamFalcon/subscriptions", "organizations_url": "https://api.github.com/users/williamFalcon/orgs", "repos_url": "https://api.github.com/users/williamFalcon/repos", "events_url": "https://api.github.com/users/williamFalcon/events{/privacy}", "received_events_url": "https://api.github.com/users/williamFalcon/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/19/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/19/timeline", "performed_via_github_app": null}