{"url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/3", "repository_url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning", "labels_url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/3/labels{/name}", "comments_url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/3/comments", "events_url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/3/events", "html_url": "https://github.com/PyTorchLightning/pytorch-lightning/issues/3", "id": 428409692, "node_id": "MDU6SXNzdWU0Mjg0MDk2OTI=", "number": 3, "title": "Issue install the library", "user": {"login": "sara-02", "id": 7047079, "node_id": "MDQ6VXNlcjcwNDcwNzk=", "avatar_url": "https://avatars.githubusercontent.com/u/7047079?v=4", "gravatar_id": "", "url": "https://api.github.com/users/sara-02", "html_url": "https://github.com/sara-02", "followers_url": "https://api.github.com/users/sara-02/followers", "following_url": "https://api.github.com/users/sara-02/following{/other_user}", "gists_url": "https://api.github.com/users/sara-02/gists{/gist_id}", "starred_url": "https://api.github.com/users/sara-02/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/sara-02/subscriptions", "organizations_url": "https://api.github.com/users/sara-02/orgs", "repos_url": "https://api.github.com/users/sara-02/repos", "events_url": "https://api.github.com/users/sara-02/events{/privacy}", "received_events_url": "https://api.github.com/users/sara-02/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2019-04-02T19:46:57Z", "updated_at": "2019-04-03T13:07:43Z", "closed_at": "2019-04-03T13:07:43Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hey, I wanted to give this library a try, so I  did `pip install pytorch-lightning`, which gave the following error\r\n```\r\nC:\\Users\\cs>pip install pytorch-lightning\r\nCollecting pytorch-lightning\r\n  Using cached https://files.pythonhosted.org/packages/7e/3e/599dfe7b8c35ef9c72d\r\nf4825d876c023fafe5e2618483ee3f3f2f4cdc3a9/pytorch-lightning-0.0.2.tar.gz\r\nCollecting test-tube (from pytorch-lightning)\r\n  Using cached https://files.pythonhosted.org/packages/3a/50/47ea5613be804c8e6e0\r\nb01b1719e1f8186b8bc626441002b141c8a962abb/test_tube-0.631.tar.gz\r\nCollecting torch (from pytorch-lightning)\r\n  Using cached https://files.pythonhosted.org/packages/5f/e9/bac4204fe9cb1a002ec\r\n6140b47f51affda1655379fe302a1caef421f9846/torch-0.1.2.post1.tar.gz\r\n    Complete output from command python setup.py egg_info:\r\n    Traceback (most recent call last):\r\n      File \"<string>\", line 1, in <module>\r\n      File \"C:\\Users\\cs\\AppData\\Local\\Temp\\pip-install-bufxsmuo\\torch\\setup.py\",\r\n line 11, in <module>\r\n        raise RuntimeError(README)\r\n    RuntimeError: PyTorch does not currently provide packages for PyPI (see stat\r\nus at https://github.com/pytorch/pytorch/issues/566).\r\n\r\n    Please follow the instructions at http://pytorch.org/ to install with minico\r\nnda instead.\r\n\r\n\r\n    ----------------------------------------\r\nCommand \"python setup.py egg_info\" failed with error code 1 in C:\\Users\\cs\\AppDa\r\nta\\Local\\Temp\\pip-install-bufxsmuo\\torch\\\r\n\r\nC:\\Users\\cs>\r\n```\r\nSo I went to the `pytorch.org`, and got the following set of commands to install pytorch on my system\r\n```\r\npip3 install https://download.pytorch.org/whl/cpu/torch-1.0.1-cp37-cp37m-win_amd64.whl\r\npip3 install torchvision\r\n\r\n```\r\nThe first command generated an error\r\n```\r\nC:\\Users\\cs>pip3 install https://download.pytorch.org/whl/cpu/torch-1.0.1-cp37-c\r\np37m-win_amd64.whl\r\ntorch-1.0.1-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.\r\n\r\nC:\\Users\\cs>\r\n```\r\nNow the only option for me is install pytorch from source code. I was wonder if we can provide the pytorch-lighting as a docker image. We provide a template docker file  for people to only provide the path for the `test_python.py` file. Is it a viable option?\r\n\r\nMy system: Windows 7, 32-bit, Python 3.7", "closed_by": {"login": "williamFalcon", "id": 3640001, "node_id": "MDQ6VXNlcjM2NDAwMDE=", "avatar_url": "https://avatars.githubusercontent.com/u/3640001?v=4", "gravatar_id": "", "url": "https://api.github.com/users/williamFalcon", "html_url": "https://github.com/williamFalcon", "followers_url": "https://api.github.com/users/williamFalcon/followers", "following_url": "https://api.github.com/users/williamFalcon/following{/other_user}", "gists_url": "https://api.github.com/users/williamFalcon/gists{/gist_id}", "starred_url": "https://api.github.com/users/williamFalcon/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/williamFalcon/subscriptions", "organizations_url": "https://api.github.com/users/williamFalcon/orgs", "repos_url": "https://api.github.com/users/williamFalcon/repos", "events_url": "https://api.github.com/users/williamFalcon/events{/privacy}", "received_events_url": "https://api.github.com/users/williamFalcon/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/3/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/3/timeline", "performed_via_github_app": null}